# Generated by Django 5.2.1 on 2025-06-03 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RonakVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ronaks/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Type 1'), ('GR', 'Type 2'), ('KL', 'Type 3'), ('PL', 'Type 4'), ('EL', 'Type 5')], default='ML', max_length=2)),
            ],
        ),
    ]
