# Generated by Django 5.2.1 on 2025-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronakvarity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
